config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  # # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :produtos, only: [ :new, :create, :destroy, :edit, :update ]
  get "/produtos/busca" => "produtos#busca", as: :busca_produto
  root "produtos#index"


  # # get "[o nome que queremos para a URL]" => "[nome do Controller]#[nome da página]"
  # get "produtos" => "produtos#index"

  # get "/produtos/new" => "produtos#new"
  # post "/produtos" => "produtos#create"

  # # get "/produtos/:id/remove" => "produtos#destroy"
  # delete "/produtos/:id" => "produtos#destroy", as: :produto

  # # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # # Defines the root path route ("/")
  # # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :departamento

  validates :quantidade, presence: true
  validates :nome, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[ show edit update destroy ]

  # GET /departamentos or /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1 or /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos or /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: "Departamento was successfully created." }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1 or /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: "Departamento was successfully updated." }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1 or /departamentos/1.json
  def destroy
    @departamento.destroy!

    respond_to do |format|
      format.html { redirect_to departamentos_path, status: :see_other, notice: "Departamento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.expect(departamento: [ :nome ])
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :busca_produto, only: [ :edit, :update, :destroy ]
  def index
    @produtos_por_nome = Produto.order(:nome).limit 5
    @produtos_por_preco = Produto.order :preco
  end


  def new
    @produto = Produto.new
    renderiza :new
  end


  def busca
    # nome_a_buscar = "%#{params[:nome]}%"
    # @produtos = Produto.where "nome like ?", nome_a_buscar

    @nome_a_buscar = params[:nome]
    @produtos = Produto.where "nome like ?", "%#{@nome_a_buscar}%"
  end

  def edit
    # busca_produto
    renderiza :edit
  end

  def update
    # busca_produto
    if @produto.update produto_params
      flash[:notice] = "Produto atualizado com sucesso"
      redirect_to root_url
    else
      renderiza :edit
    end
  end


  def create
    @produto = Produto.new produto_params

    if @produto.save
      flash[:notice] = "Produto salvo com sucesso"
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    # id = params[:id]
    # Produto.destroy id
    # redirect_to root_url

    # busca_produto
    @produto.destroy
    redirect_to root_url
  end

  private
  def renderiza(view)
    @departamentos = Departamento.all
    render view
  end

  def busca_produto
    id = params[:id]
    @produto = Produto.find(id)
  end

  def produto_params
    params.require(:produto).permit :nome, :preco, :descricao, :quantidade, :departamento_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_departamento.html.erb
<div id="<%= dom_id departamento %>">
  <p>
    <strong>Nome:</strong>
    <%= departamento.nome %>
  </p>

</div>

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento) do |form| %>
  <% if departamento.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
        <% departamento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<% content_for :title, "Editing departamento" %>

<h1>Editing departamento</h1>

<%= render "form", departamento: @departamento %>

<br>

<div>
  <%= link_to "Show this departamento", @departamento %> |
  <%= link_to "Back to departamentos", departamentos_path %>
</div>

app/views/departamentos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Departamentos" %>

<h1>Departamentos</h1>

<div id="departamentos">
  <% @departamentos.each do |departamento| %>
    <%= render departamento %>
    <p>
      <%= link_to "Show this departamento", departamento %>
    </p>
  <% end %>
</div>

<%= link_to "New departamento", new_departamento_path %>

app/views/departamentos/new.html.erb
<% content_for :title, "New departamento" %>

<h1>New departamento</h1>

<%= render "form", departamento: @departamento %>

<br>

<div>
  <%= link_to "Back to departamentos", departamentos_path %>
</div>

app/views/departamentos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @departamento %>

<div>
  <%= link_to "Edit this departamento", edit_departamento_path(@departamento) %> |
  <%= link_to "Back to departamentos", departamentos_path %>

  <%= button_to "Destroy this departamento", @departamento, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Loja de camisetas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <!-- PWA manifest - pode remover se não estiver usando -->
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <!-- Inclusão do arquivo CSS do Bootstrap -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>

    <!-- Inclusão do arquivo JavaScript (para Sprockets) -->
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <!-- Barra de navegação com a marca Kunstee -->
<nav class="navbar navbar-dark bg-dark px-4">
  <a class="navbar-brand" href="<%= root_url %>">Kunstee</a>
  <%= form_tag busca_produto_path, method: :get, class: "ml-auto d-flex align-items-center" do %>
    <%= text_field_tag :nome, params[:nome], class: "form-control mr-2", placeholder: "Buscar" %>
    <%= submit_tag "Buscar", class: "btn btn-outline-light" %>
  <% end %>
</nav>







    <div class="container">
          <%= yield %>
    </div>
  </body>
</html>

app/views/produtos/_form.html.erb
<!---Mensagem de erro --->
<% @produto.errors.full_messages.each do |message|%>
    <div class="alert alert-danger" role="alert"><%=message%></div>
<%end%>

<%= form_for @produto do |f| %>

    <div class="form-group">
        <%= f.label :nome %>
        <%= f.text_field :nome, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :descricao %>
        <%= f.text_area :descricao, rows: 4, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :departamento%>
        <%= f.collection_select :departamento_id, @departamentos, :id, :nome,
        {}, class: "form-control" %>
    </div>

    <div class="form-inline">
        <div class="form-group">
            <%= f.label :quantidade %>
            <%= f.number_field :quantidade, step: 1, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :preco %>
            <%= f.number_field :preco, step: 0.1, class: "form-control" %>
        </div>

        <%= f.submit texto_da_acao, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/produtos/_produto.html.erb
<tr>
    <td><%= produto.nome %></td>
    <td><%= produto.descricao %></td>
    <td><%= produto.preco %></td>
    <td>
        <%=button_to "Remover", produto, 
                                    method: :delete,
                                    class: "btn btn-danger",
                                    data: {confirm: "Deseja remover #{produto.nome}?"}%>
    </td>
    <!-- <td><a href = "/produtos/<%= produto.id%>/remove">Remover</td> -->


    <td>
        <%= link_to "Editar", edit_produto_path(produto),
                                    class: "btn btn-default"
                                    %>
    </td>

</tr>

app/views/produtos/busca.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Preço</th>
    </tr>
  </thead>
  <tbody>
    <!--<%= render partial: "produto" , collection: @produtos%> -->
    <%= render @produtos%>
  </tbody>
</table>

app/views/produtos/edit.html.erb
<%= render partial: 'form', locals: {texto_da_acao: "Atualizar o produto" }%>

app/views/produtos/index.html.erb
<% if flash[:notice]%>
  <div class="alert alert-success" role="alert"><%= flash[:notice]%></div>
<% end %>
<div class="container mt-5">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Preço</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "produto", collection: @produtos_por_nome%>
    </tbody>
  </table>

  <table class="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Preço</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "produto", collection: @produtos_por_preco%>
  </tbody>
</table>
<%=link_to "Criar novo produto", new_produto_path%>
</div>

app/views/produtos/new.html.erb
<%= render partial: 'form', locals: {texto_da_acao: "Criar o produto" }%>